version: '3'
services:
  nginx:
    image: "nginx:alpine"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/opt/app
    links:
      - web
    environment:
      VIRTUAL_HOST: ".wetrust.cl"
      LETSENCRYPT_HOST: ".wetrust.cl"
      LETSENCRYPT_EMAIL: "cristopher@wetrust.cl"
  web:
    build:
        context: .
        dockerfile: web.dockerfile
    image: web:latest
    volumes:
      - .:/opt/app
      #solo si php necesita más memoria o subir archivos más grandes
      #- ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
networks:
  default:
    external:
      name: "wetrust"