<?php
error_reporting(E_ALL);
ini_set("display_errors", 1);

return array(
    'URL' => 'http://' . $_SERVER['HTTP_HOST'] . str_replace('public', '', dirname($_SERVER['SCRIPT_NAME'])),
    'PATH_CONTROLLER' => realpath(dirname(__FILE__).'/../../') . '/application/controller/',
    'PATH_VIEW' => realpath(dirname(__FILE__).'/../../') . '/application/view/',
    'PATH_AVATARS' => realpath(dirname(__FILE__).'/../../') . '/public/avatars/',
    'PATH_AVATARS_PUBLIC' => 'avatars/',
    'DEFAULT_CONTROLLER' => 'index',
    'DEFAULT_ACTION' => 'index',
    'DB_TYPE' => 'mysql',
    'DB_HOST' => 'db',
    'DB_NAME' => 'huge',
    'DB_USER' => 'root',
    'DB_PASS' => 'test',
    'DB_PORT' => '3306',
    'DB_CHARSET' => 'utf8',
    'CAPTCHA_WIDTH' => 359,
    'CAPTCHA_HEIGHT' => 100,
    'COOKIE_RUNTIME' => 1209600,
    'COOKIE_PATH' => '/',
    'COOKIE_DOMAIN' => "",
    'COOKIE_SECURE' => false,
    'COOKIE_HTTP' => true,
    'COOKIE_NAME' => "PHPSESSID",
    'SESSION_RUNTIME' => 604800,
    'USE_GRAVATAR' => false,
    'GRAVATAR_DEFAULT_IMAGESET' => 'mm',
    'GRAVATAR_RATING' => 'pg',
    'AVATAR_SIZE' => 44,
    'AVATAR_JPEG_QUALITY' => 85,
    'AVATAR_DEFAULT_IMAGE' => 'default.jpg',
    'ENCRYPTION_KEY' => '6#x0gÊìf^25cL1f$08&',
    'HMAC_SALT' => '8qk9c^4L6d#15tM8z7n0%',
    'EMAIL_USED_MAILER' => 'phpmailer',
    'EMAIL_USE_SMTP' => true,
    'EMAIL_SMTP_HOST' => 'email-smtp.sa-east-1.amazonaws.com',
    'EMAIL_SMTP_HOST' => 'smtp.gmail.com',
    'EMAIL_SMTP_AUTH' => true,
    'EMAIL_SMTP_USERNAME' => '',
    'EMAIL_SMTP_PASSWORD' => '',
    'EMAIL_SMTP_PORT' => 587,
    'EMAIL_FROM' => 'no-reply@wetrust.cl',
    'EMAIL_FROM_NAME' => 'Simple',
    'EMAIL_PASSWORD_RESET_URL' => 'login/verifypasswordreset',
    'EMAIL_PASSWORD_RESET_SUBJECT' => 'Cambiar contraseña',
    'EMAIL_PASSWORD_RESET_CONTENT' => 'Haga click en el siguiente link para cambiar su contraseña: ',
    'EMAIL_VERIFICATION_URL' => 'register/verify',
    'EMAIL_VERIFICATION_SUBJECT' => 'Verificación de cuenta',
    'EMAIL_VERIFICATION_CONTENT' => 'Haga click en el siguiente link para activar su cuenta: ',
);